name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  buck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Download buckle
        run: |
          curl -OL https://github.com/benbrittain/buckle/releases/download/v1.1.0/buckle-x86_64-unknown-linux-gnu.tar.xz
          tar -Jxvf buckle-x86_64-unknown-linux-gnu.tar.xz

      - uses: TraceMachina/nativelink-action@c521ecfd7eaded6f0bbc9060c21c7b5b7cd2dc1e
        with:
          api_key: ${{ secrets.NATIVELINK_API_KEY }}
          account: tom-parker-shemilt
          prefix: tom-parker-shemilt-y0738m
          build_system: buck2

      - run: buckle-x86_64-unknown-linux-gnu/buckle build //...
